services:
  app:
    image: drogonframework/drogon 
    container_name: drogon 
    ports:
      - 80:80
    volumes: 
        - ./:/app
    tty: true
    working_dir: /app

  mysql:
    container_name: db 
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=blog
      - MYSQL_USER=blog
      - MYSQL_PASSWORD=blog
      - MYSQL_ROOT_PASSWORD=root
      - TZ=UTC
    command: --default-authentication-plugin=mysql_native_password
    ports:
     - 3307:3306

volumes:
  mysql_data:
